/**
 * Built-in offline "demo analyst" provider.
 *
 * Speaks the exact same JSON contract as the real providers, so the whole
 * pipeline (validation, ops application, versioning) is identical with or
 * without an API key. Useful for trying the product, for demos, and for
 * deterministic tests.
 */
import { sampleOrderFulfilmentMap } from '@eatransform/shared';

const IDS = { n: 0 };
const nid = (p = 'n') => `${p}_mock${++IDS.n}`;

function buildMap({ name, purpose, objective, owner, lanes, steps, kpis, risks }) {
  // steps: [laneIdx, type, label, extra]
  const laneObjs = lanes.map((l, i) => ({ id: nid('lane'), name: l[0], kind: l[1] || 'department', order: i }));
  const nodes = steps.map(([laneIdx, type, label, extra]) => ({
    id: nid(),
    type,
    label,
    laneId: laneObjs[laneIdx].id,
    ...(extra || {}),
  }));
  const edges = [];
  for (let i = 0; i < nodes.length - 1; i++) {
    edges.push({ id: nid('e'), source: nodes[i].id, target: nodes[i + 1].id });
  }
  return {
    name,
    type: 'swimlane',
    purpose,
    objective,
    owner,
    level: 1,
    departments: laneObjs.filter((l) => l.kind === 'department').map((l) => l.name),
    stakeholders: laneObjs.map((l) => l.name),
    lanes: laneObjs,
    nodes,
    edges,
    kpis,
    risks,
    metadata: { generatedBy: 'mock-analyst', notes: 'Generated by the offline demo analyst.' },
  };
}

function patientOnboardingMap() {
  return buildMap({
    name: 'Patient Onboarding',
    purpose: 'Register, assess and admit new patients smoothly and safely.',
    objective: 'Improve patient onboarding speed and experience.',
    owner: 'Patient Services Manager',
    lanes: [
      ['Patient', 'customer'],
      ['Reception & Registration', 'department'],
      ['Clinical Team', 'department'],
      ['Insurance & Billing', 'department'],
    ],
    steps: [
      [0, 'start', 'Patient requests appointment'],
      [1, 'task', 'Capture patient details', { automation: 'semi-automated', durationMins: 10, systems: ['EHR'] }],
      [3, 'task', 'Verify insurance eligibility', { automation: 'manual', durationMins: 15, waitMins: 120, risks: [{ name: 'Coverage rejection discovered late', severity: 'high' }] }],
      [2, 'decision', 'Triage: urgent case?'],
      [2, 'task', 'Initial clinical assessment', { durationMins: 30, owner: 'Nurse practitioner' }],
      [2, 'approval', 'Consultant sign-off on care plan', { durationMins: 10, waitMins: 240 }],
      [1, 'task', 'Schedule treatment & send welcome pack', { automation: 'semi-automated', durationMins: 10 }],
      [0, 'event', 'Patient confirmed'],
      [0, 'end', 'Patient onboarded'],
    ],
    kpis: [
      { name: 'Registration-to-admission time', target: '48', unit: 'hours' },
      { name: 'First-visit no-show rate', target: '≤ 5', unit: '%' },
    ],
    risks: [{ name: 'Incomplete patient data at registration', severity: 'medium', mitigation: 'Mandatory field validation in EHR' }],
  });
}

function productionWasteMap() {
  return buildMap({
    name: 'Production & Waste Reduction',
    purpose: 'Manufacture product while minimising scrap and rework.',
    objective: 'Reduce production waste.',
    owner: 'Plant Manager',
    lanes: [
      ['Planning', 'department'],
      ['Production Line', 'department'],
      ['Quality Assurance', 'department'],
      ['Warehouse & Dispatch', 'department'],
    ],
    steps: [
      [0, 'start', 'Production order released'],
      [0, 'task', 'Material requirements check', { automation: 'automated', systems: ['ERP'], durationMins: 5 }],
      [1, 'task', 'Machine setup & calibration', { durationMins: 45, risks: [{ name: 'Setup error causes scrap batch', severity: 'high', mitigation: 'Standard setup checklist' }] }],
      [1, 'task', 'Production run', { durationMins: 240, kpis: [{ name: 'First-pass yield', target: '≥ 97', unit: '%' }] }],
      [2, 'decision', 'In-line inspection pass?'],
      [1, 'task', 'Rework / scrap handling', { durationMins: 60, waitMins: 120, risks: [{ name: 'Rework loop hides root causes', severity: 'medium' }] }],
      [2, 'approval', 'Final quality release', { durationMins: 15 }],
      [3, 'task', 'Pack & move to warehouse', { durationMins: 20 }],
      [3, 'end', 'Goods ready for dispatch'],
    ],
    kpis: [
      { name: 'Scrap rate', target: '≤ 2', unit: '%' },
      { name: 'OEE', target: '≥ 85', unit: '%' },
    ],
    risks: [{ name: 'Raw material variability', severity: 'high', mitigation: 'Supplier quality agreements' }],
  });
}

function pickTemplate(text) {
  const t = text.toLowerCase();
  if (/(health|patient|clinic|hospital|care)/.test(t)) return patientOnboardingMap();
  if (/(manufactur|production|factory|waste|plant|assembly)/.test(t)) return productionWasteMap();
  const map = JSON.parse(JSON.stringify(sampleOrderFulfilmentMap()));
  map.metadata = { generatedBy: 'mock-analyst' };
  return map;
}

function fuzzyFindNode(map, phrase) {
  const p = phrase.toLowerCase().replace(/[^a-z0-9 ]/g, '').trim();
  if (!p) return null;
  let best = null;
  let bestScore = 0;
  for (const n of map.nodes) {
    const label = n.label.toLowerCase();
    const words = p.split(/\s+/).filter((w) => w.length > 2);
    const score = words.filter((w) => label.includes(w)).length / Math.max(1, words.length);
    if (score > bestScore) {
      best = n;
      bestScore = score;
    }
  }
  return bestScore >= 0.5 ? best : null;
}

function needsClarification(message, history) {
  const userTurns = history.filter((m) => m.role === 'user').length;
  if (userTurns > 0) return false; // already answered once — proceed
  const words = message.trim().split(/\s+/).length;
  const hasGoal = /(reduce|improve|increase|speed|faster|cut|optimi|lower|grow|fix|onboard)/i.test(message);
  return words < 10 || !hasGoal;
}

function intake({ message, history }) {
  if (needsClarification(message, history)) {
    return {
      action: 'ask',
      message:
        'Before I build your process map, I need a little more context. Could you answer these briefly?',
      questions: [
        { question: 'What does your organisation do, and what is the main objective you want to achieve?', why: 'The objective drives which process and KPIs matter most.' },
        { question: 'Which teams or departments are involved end-to-end?', why: 'These become the swimlanes and clarify handoffs.' },
        { question: 'Where do you feel the biggest pain today (delays, errors, cost, compliance)?', why: 'It tells me where to focus improvement analysis.' },
      ],
    };
  }
  const allText = history.filter((m) => m.role === 'user').map((m) => m.text).concat(message).join(' ');
  const map = pickTemplate(allText);
  return {
    action: 'generate',
    message:
      `I have drafted "${map.name}" as a cross-functional swimlane map based on your description. ` +
      'Every element is editable — select any activity, lane or connection, or just tell me what to change. ' +
      '(Demo analyst note: with a real AI key configured, this map would be tailored precisely to your wording.)',
    processMap: map,
  };
}

function edit({ message, map, analysis }) {
  const t = message.toLowerCase();

  if (/highlight.*(bottleneck|delay|wait)/.test(t)) {
    return {
      action: 'highlight',
      nodeIds: (analysis?.bottlenecks || []).map((b) => b.nodeId),
      message: `I highlighted ${analysis?.bottlenecks?.length || 0} bottleneck step(s) on the canvas — see the Insights tab for the reasons behind each.`,
    };
  }

  let m = t.match(/add (?:a |an )?(.+?) (before|after) (?:the )?(.+)/);
  if (m) {
    const [, what, where, anchorPhrase] = m;
    const anchor = fuzzyFindNode(map, anchorPhrase);
    if (!anchor) {
      return { action: 'answer', message: `I could not find an activity matching "${anchorPhrase.trim()}". Could you use the exact activity name shown on the map?` };
    }
    const type = /approval|sign-?off|authori/.test(what) ? 'approval' : /decision|check\?/.test(what) ? 'decision' : 'task';
    const label = what.replace(/\b\w/, (c) => c.toUpperCase());
    const ops = [];
    if (where === 'before') {
      const incoming = map.edges.find((e) => e.target === anchor.id);
      ops.push(
        incoming
          ? { op: 'add_node', node: { type, label, laneId: anchor.laneId }, betweenSource: incoming.source, betweenTarget: anchor.id }
          : { op: 'add_node', node: { type, label, laneId: anchor.laneId } }
      );
      if (!incoming) ops.push({ op: 'add_edge', edge: { source: 'PENDING', target: anchor.id } });
    } else {
      ops.push({ op: 'add_node', node: { type, label, laneId: anchor.laneId }, afterNodeId: anchor.id });
    }
    return { action: 'edit', operations: ops.filter((o) => o.op === 'add_node'), message: `Added ${type} "${label}" ${where} "${anchor.label}".` };
  }

  m = t.match(/(?:remove|delete) (?:the )?(.+)/);
  if (m) {
    const node = fuzzyFindNode(map, m[1]);
    if (!node) return { action: 'answer', message: `I could not find an activity matching "${m[1].trim()}".` };
    return { action: 'edit', operations: [{ op: 'remove_node', id: node.id }], message: `Removed "${node.label}" and reconnected the flow around it.` };
  }

  m = t.match(/rename (?:the )?(.+?) to (.+)/);
  if (m) {
    const node = fuzzyFindNode(map, m[1]);
    if (!node) return { action: 'answer', message: `I could not find an activity matching "${m[1].trim()}".` };
    const label = m[2].trim().replace(/\b\w/, (c) => c.toUpperCase());
    return { action: 'edit', operations: [{ op: 'update_node', id: node.id, changes: { label } }], message: `Renamed "${node.label}" to "${label}".` };
  }

  m = t.match(/split (?:the )?(.+?) (?:lane |swimlane )?into (\w+|\d+) teams?/);
  if (m) {
    const lane = map.lanes.find((l) => l.name.toLowerCase().includes(m[1].replace(/lane|swimlane/g, '').trim()));
    const count = { two: 2, three: 3, four: 4 }[m[2]] || Number(m[2]) || 2;
    if (!lane) return { action: 'answer', message: `I could not find a swimlane matching "${m[1].trim()}".` };
    const nodesIn = map.nodes.filter((n) => n.laneId === lane.id).map((n) => n.id);
    const newLanes = Array.from({ length: Math.min(count, Math.max(2, count)) }, (_, i) => ({
      name: `${lane.name} — Team ${i + 1}`,
      nodeIds: nodesIn.filter((_, j) => j % count === i),
    }));
    return { action: 'edit', operations: [{ op: 'split_lane', id: lane.id, newLanes }], message: `Split "${lane.name}" into ${count} team lanes.` };
  }

  if (/(reduce|remove).*(approval|sign-?off)/.test(t) || /optimi[sz]e/.test(t)) {
    const approvals = map.nodes.filter((n) => n.type === 'approval');
    const ops = [];
    let msg = '';
    if (/(reduce|remove).*(approval|sign-?off)/.test(t) && approvals.length > 1) {
      ops.push({ op: 'remove_node', id: approvals[approvals.length - 1].id });
      msg += `Removed the "${approvals[approvals.length - 1].label}" approval (the process retains ${approvals.length - 1} control point). `;
    }
    for (const n of map.nodes.filter((x) => x.automation === 'manual' && x.type === 'task').slice(0, 2)) {
      ops.push({ op: 'update_node', id: n.id, changes: { automation: 'semi-automated' } });
      msg += `Marked "${n.label}" for semi-automation. `;
    }
    if (ops.length === 0) return { action: 'answer', message: 'I reviewed the process — there are no redundant approvals to remove, and manual steps are already minimal. See Insights for remaining recommendations.' };
    return { action: 'edit', operations: ops, message: msg.trim() };
  }

  if (/executive summary|summari[sz]e/.test(t)) {
    const a = analysis || {};
    return {
      action: 'answer',
      message:
        `EXECUTIVE SUMMARY — ${map.name}\n\n` +
        `Purpose: ${map.purpose || '—'}\nObjective: ${map.objective || '—'}\nOwner: ${map.owner || 'unassigned'}\n\n` +
        `The process spans ${map.lanes.length} functions with ${map.nodes.length} activities and ${a.counts?.handoffs ?? '—'} cross-team handoffs. ` +
        `Health score is ${a.healthScore ?? '—'}/100 with ${a.bottlenecks?.length ?? 0} bottleneck(s) identified.\n\n` +
        `Top recommendations:\n${(a.recommendations || []).slice(0, 4).map((r) => `• ${r}`).join('\n') || '• None'}`,
    };
  }

  if (/iso|complian/.test(t)) {
    return {
      action: 'edit',
      operations: [
        { op: 'update_process', changes: { compliance: [...new Set([...(map.compliance || []), 'ISO 9001: documented procedure & records control'])] } },
      ],
      message: 'Tagged the process with ISO 9001 compliance requirements. For full ISO readiness, ensure each activity lists its controlling document — I can add document nodes if you name the SOPs.',
    };
  }

  return {
    action: 'answer',
    message:
      'Demo analyst: I understood your message but this particular request needs the full AI provider. ' +
      'I can handle: "add X before/after Y", "remove X", "rename X to Y", "split LANE into N teams", ' +
      '"reduce approvals", "optimise this process", "highlight bottlenecks", "create an executive summary". ' +
      'Add an AI key in .env for unrestricted natural-language editing.',
  };
}

function insights({ analysis, map }) {
  const a = analysis;
  return {
    narrative:
      `Consultant review of "${map.name}" (demo analyst):\n\n` +
      `This process scores ${a.healthScore}/100. Complexity is ${a.complexityLabel.toLowerCase()} ` +
      `(${a.counts.nodes} activities across ${a.counts.lanes} lanes with ${a.counts.handoffs} handoffs).\n\n` +
      `${a.bottlenecks.length ? `The critical constraint appears to be: ${a.bottlenecks.map((b) => b.label).join(', ')}. ` : ''}` +
      `${a.counts.manualTasks} of ${a.counts.activities} activities are manual — ${a.automationOpportunities.slice(0, 2).map((o) => o.label).join(' and ') || 'none'} are the strongest automation candidates.\n\n` +
      `Priority actions:\n${a.recommendations.map((r) => `• ${r}`).join('\n')}`,
  };
}

export function createMockProvider() {
  return {
    name: 'mock',
    model: 'mock-analyst-1',
    async complete({ hint }) {
      if (!hint) throw new Error('Mock provider requires a structured hint');
      let out;
      if (hint.action === 'intake') out = intake(hint.payload);
      else if (hint.action === 'edit') out = edit(hint.payload);
      else if (hint.action === 'insights') out = insights(hint.payload);
      else out = { action: 'answer', message: 'Demo analyst ready.' };
      return JSON.stringify(out);
    },
  };
}
