/** Realistic sample process map used by tests, seeds, and the offline mock analyst. */
import { ProcessMapSchema } from './schema.js';

export function sampleOrderFulfilmentMap() {
  return ProcessMapSchema.parse({
    name: 'Order Fulfilment & Delivery',
    type: 'swimlane',
    purpose: 'Fulfil online clothing orders from checkout to doorstep.',
    objective: 'Reduce delivery delays and improve on-time delivery to 95%.',
    owner: 'Head of Operations',
    level: 1,
    stakeholders: ['Customer', 'Operations', 'Warehouse', 'Courier partner', 'Finance'],
    departments: ['Sales', 'Warehouse', 'Logistics', 'Finance'],
    customers: ['Online shopper'],
    suppliers: ['Courier partner'],
    lanes: [
      { id: 'lane_cust', name: 'Customer', kind: 'customer', order: 0 },
      { id: 'lane_sales', name: 'Sales & Service', kind: 'department', order: 1 },
      { id: 'lane_wh', name: 'Warehouse', kind: 'department', order: 2 },
      { id: 'lane_log', name: 'Logistics', kind: 'department', order: 3 },
      { id: 'lane_fin', name: 'Finance', kind: 'department', order: 4 },
    ],
    nodes: [
      { id: 'n_start', type: 'start', label: 'Order placed', laneId: 'lane_cust' },
      {
        id: 'n_validate',
        type: 'task',
        label: 'Validate order & payment',
        laneId: 'lane_sales',
        automation: 'automated',
        systems: ['E-commerce platform', 'Payment gateway'],
        durationMins: 2,
        outputs: ['Confirmed order'],
      },
      {
        id: 'n_stock',
        type: 'decision',
        label: 'Stock available?',
        laneId: 'lane_wh',
        durationMins: 1,
      },
      {
        id: 'n_backorder',
        type: 'task',
        label: 'Raise backorder with supplier',
        laneId: 'lane_wh',
        automation: 'manual',
        waitMins: 2880,
        risks: [{ name: 'Supplier lead time slippage', severity: 'high' }],
      },
      {
        id: 'n_pick',
        type: 'task',
        label: 'Pick & pack order',
        laneId: 'lane_wh',
        automation: 'manual',
        durationMins: 15,
        inputs: ['Pick list'],
        outputs: ['Packed parcel'],
        kpis: [{ name: 'Pick accuracy', target: '99.5', unit: '%' }],
      },
      {
        id: 'n_qc',
        type: 'approval',
        label: 'Quality check & release',
        laneId: 'lane_wh',
        automation: 'manual',
        durationMins: 5,
        controls: ['Barcode scan verification'],
      },
      {
        id: 'n_book',
        type: 'task',
        label: 'Book courier collection',
        laneId: 'lane_log',
        automation: 'semi-automated',
        durationMins: 5,
        waitMins: 240,
        systems: ['Courier portal'],
        risks: [{ name: 'Missed courier cut-off', severity: 'medium', mitigation: 'Earlier daily cut-off' }],
      },
      {
        id: 'n_ship',
        type: 'subprocess',
        label: 'Last-mile delivery',
        laneId: 'lane_log',
        description: 'Courier partner network delivery to customer address.',
        waitMins: 1440,
      },
      {
        id: 'n_invoice',
        type: 'task',
        label: 'Issue invoice & reconcile payment',
        laneId: 'lane_fin',
        automation: 'automated',
        durationMins: 1,
      },
      { id: 'n_notify', type: 'event', label: 'Delivery notification', laneId: 'lane_cust' },
      { id: 'n_end', type: 'end', label: 'Order delivered', laneId: 'lane_cust' },
    ],
    edges: [
      { id: 'e1', source: 'n_start', target: 'n_validate' },
      { id: 'e2', source: 'n_validate', target: 'n_stock' },
      { id: 'e3', source: 'n_stock', target: 'n_pick', label: 'Yes' },
      { id: 'e4', source: 'n_stock', target: 'n_backorder', label: 'No', kind: 'alternative' },
      { id: 'e5', source: 'n_backorder', target: 'n_pick' },
      { id: 'e6', source: 'n_pick', target: 'n_qc' },
      { id: 'e7', source: 'n_qc', target: 'n_book' },
      { id: 'e8', source: 'n_book', target: 'n_ship' },
      { id: 'e9', source: 'n_ship', target: 'n_notify' },
      { id: 'e10', source: 'n_ship', target: 'n_invoice' },
      { id: 'e11', source: 'n_notify', target: 'n_end' },
    ],
    kpis: [
      { name: 'On-time delivery', target: '95', unit: '%' },
      { name: 'Order-to-ship time', target: '24', unit: 'hours' },
    ],
    risks: [{ name: 'Peak season capacity shortfall', severity: 'high', mitigation: 'Temp staffing plan' }],
    dependencies: ['Courier partner SLA', 'Supplier replenishment lead times'],
    compliance: ['Consumer rights (returns within 14 days)'],
    metadata: { generatedBy: 'sample' },
  });
}
