/**
 * Core process-map data model for EATransform.
 *
 * Every process map — whether created manually or generated by AI — must
 * conform to this schema. AI responses are validated against it before they
 * are allowed anywhere near the UI or the database.
 */
import { z } from 'zod';

export const MAP_TYPES = [
  'bpmn', // BPMN 2.0-style flow
  'swimlane', // cross-functional swimlane map
  'sipoc', // Suppliers-Inputs-Process-Outputs-Customers
  'value-stream', // value stream map
  'journey', // customer journey map
  'workflow', // simple business workflow
  'raci', // RACI-annotated process view
];

export const NODE_TYPES = [
  'start',
  'end',
  'task',
  'decision',
  'approval',
  'subprocess',
  'document',
  'event',
  'wait',
  'milestone',
];

export const LANE_KINDS = [
  'department',
  'team',
  'role',
  'employee',
  'customer',
  'supplier',
  'external',
  'business-unit',
];

export const EDGE_KINDS = ['sequence', 'message', 'exception', 'alternative', 'dependency'];

export const AUTOMATION_LEVELS = ['manual', 'semi-automated', 'automated'];

const id = z.string().min(1).max(80);
const shortText = z.string().max(300);
const longText = z.string().max(4000);

export const KpiSchema = z.object({
  name: shortText,
  target: shortText.optional().default(''),
  unit: shortText.optional().default(''),
  description: longText.optional().default(''),
});

export const RiskSchema = z.object({
  name: shortText,
  severity: z.enum(['low', 'medium', 'high', 'critical']).optional().default('medium'),
  mitigation: longText.optional().default(''),
  description: longText.optional().default(''),
});

export const RaciSchema = z.object({
  responsible: shortText.optional().default(''),
  accountable: shortText.optional().default(''),
  consulted: shortText.optional().default(''),
  informed: shortText.optional().default(''),
});

export const LaneSchema = z.object({
  id,
  name: shortText,
  kind: z.enum(LANE_KINDS).optional().default('department'),
  order: z.number().int().optional().default(0),
  color: z.string().max(30).optional().default(''),
  collapsed: z.boolean().optional().default(false),
  locked: z.boolean().optional().default(false),
  height: z.number().positive().max(5000).optional().default(180),
});

export const NodeSchema = z.object({
  id,
  type: z.enum(NODE_TYPES),
  label: shortText,
  laneId: id.optional().nullable().default(null),
  description: longText.optional().default(''),
  owner: shortText.optional().default(''),
  role: shortText.optional().default(''),
  inputs: z.array(shortText).optional().default([]),
  outputs: z.array(shortText).optional().default([]),
  documents: z.array(shortText).optional().default([]),
  systems: z.array(shortText).optional().default([]),
  businessRules: z.array(longText).optional().default([]),
  risks: z.array(RiskSchema).optional().default([]),
  controls: z.array(shortText).optional().default([]),
  kpis: z.array(KpiSchema).optional().default([]),
  raci: RaciSchema.optional().default({}),
  automation: z.enum(AUTOMATION_LEVELS).optional().default('manual'),
  durationMins: z.number().nonnegative().optional().nullable().default(null),
  waitMins: z.number().nonnegative().optional().nullable().default(null),
  cost: z.number().nonnegative().optional().nullable().default(null),
  slaMins: z.number().nonnegative().optional().nullable().default(null),
  compliance: z.array(shortText).optional().default([]),
  childProcessId: z.string().optional().nullable().default(null),
  color: z.string().max(30).optional().default(''),
  position: z
    .object({ x: z.number(), y: z.number() })
    .optional()
    .nullable()
    .default(null),
  annotations: z.array(longText).optional().default([]),
});

export const EdgeSchema = z.object({
  id,
  source: id,
  target: id,
  label: shortText.optional().default(''),
  condition: shortText.optional().default(''),
  kind: z.enum(EDGE_KINDS).optional().default('sequence'),
});

export const CommentSchema = z.object({
  id,
  nodeId: id.optional().nullable().default(null),
  author: shortText.optional().default(''),
  text: longText,
  createdAt: z.string().optional().default(''),
});

export const SipocSchema = z.object({
  suppliers: z.array(shortText).optional().default([]),
  inputs: z.array(shortText).optional().default([]),
  outputs: z.array(shortText).optional().default([]),
  customers: z.array(shortText).optional().default([]),
});

export const ProcessMapSchema = z.object({
  name: shortText.min(1),
  type: z.enum(MAP_TYPES).optional().default('swimlane'),
  purpose: longText.optional().default(''),
  objective: longText.optional().default(''),
  scope: longText.optional().default(''),
  owner: shortText.optional().default(''),
  level: z.number().int().min(0).max(4).optional().default(1),
  stakeholders: z.array(shortText).optional().default([]),
  departments: z.array(shortText).optional().default([]),
  customers: z.array(shortText).optional().default([]),
  suppliers: z.array(shortText).optional().default([]),
  sipoc: SipocSchema.optional().default({}),
  lanes: z.array(LaneSchema).optional().default([]),
  nodes: z.array(NodeSchema).min(1),
  edges: z.array(EdgeSchema).optional().default([]),
  kpis: z.array(KpiSchema).optional().default([]),
  risks: z.array(RiskSchema).optional().default([]),
  dependencies: z.array(shortText).optional().default([]),
  compliance: z.array(shortText).optional().default([]),
  assumptions: z.array(longText).optional().default([]),
  comments: z.array(CommentSchema).optional().default([]),
  metadata: z
    .object({
      generatedBy: z.string().optional().default('manual'),
      notes: longText.optional().default(''),
    })
    .passthrough()
    .optional()
    .default({}),
});

/**
 * Structural validation that Zod alone cannot express:
 * referenced ids must exist, the graph must have starts/ends, etc.
 * Returns { ok, errors: string[], warnings: string[] }.
 */
export function validateMapStructure(map) {
  const errors = [];
  const warnings = [];
  const nodeIds = new Set();
  for (const n of map.nodes) {
    if (nodeIds.has(n.id)) errors.push(`Duplicate node id "${n.id}"`);
    nodeIds.add(n.id);
  }
  const laneIds = new Set();
  for (const l of map.lanes) {
    if (laneIds.has(l.id)) errors.push(`Duplicate lane id "${l.id}"`);
    laneIds.add(l.id);
  }
  for (const n of map.nodes) {
    if (n.laneId && !laneIds.has(n.laneId)) {
      errors.push(`Node "${n.label}" references missing lane "${n.laneId}"`);
    }
  }
  const edgeIds = new Set();
  for (const e of map.edges) {
    if (edgeIds.has(e.id)) errors.push(`Duplicate edge id "${e.id}"`);
    edgeIds.add(e.id);
    if (!nodeIds.has(e.source)) errors.push(`Edge "${e.id}" has missing source "${e.source}"`);
    if (!nodeIds.has(e.target)) errors.push(`Edge "${e.id}" has missing target "${e.target}"`);
    if (e.source === e.target) warnings.push(`Edge "${e.id}" loops onto the same node`);
  }
  const starts = map.nodes.filter((n) => n.type === 'start');
  const ends = map.nodes.filter((n) => n.type === 'end');
  if (starts.length === 0) warnings.push('Process has no start event');
  if (ends.length === 0) warnings.push('Process has no end event');
  // orphan detection (only when there are edges at all)
  if (map.edges.length > 0) {
    const connected = new Set();
    for (const e of map.edges) {
      connected.add(e.source);
      connected.add(e.target);
    }
    for (const n of map.nodes) {
      if (!connected.has(n.id) && n.type !== 'milestone') {
        warnings.push(`Node "${n.label}" is not connected to the flow`);
      }
    }
  }
  return { ok: errors.length === 0, errors, warnings };
}

/**
 * Best-effort automatic repair of a structurally broken map (typically from
 * an AI response): drops dangling edges, de-duplicates ids, fixes missing
 * lane references. Returns a repaired copy.
 */
export function repairMapStructure(map) {
  const out = JSON.parse(JSON.stringify(map));
  // de-dupe node ids
  const seen = new Set();
  for (const n of out.nodes) {
    let nid = n.id;
    let i = 2;
    while (seen.has(nid)) nid = `${n.id}-${i++}`;
    n.id = nid;
    seen.add(nid);
  }
  const laneIds = new Set(out.lanes.map((l) => l.id));
  for (const n of out.nodes) {
    if (n.laneId && !laneIds.has(n.laneId)) n.laneId = null;
  }
  const nodeIds = new Set(out.nodes.map((n) => n.id));
  out.edges = out.edges.filter((e) => nodeIds.has(e.source) && nodeIds.has(e.target));
  const seenEdges = new Set();
  for (const e of out.edges) {
    let eid = e.id;
    let i = 2;
    while (seenEdges.has(eid)) eid = `${e.id}-${i++}`;
    e.id = eid;
    seenEdges.add(eid);
  }
  return out;
}

/**
 * Parse + validate + (if needed) repair an untrusted candidate process map.
 * Returns { ok: true, map, warnings } or { ok: false, errors }.
 */
export function parseProcessMap(candidate) {
  const parsed = ProcessMapSchema.safeParse(candidate);
  if (!parsed.success) {
    return {
      ok: false,
      errors: parsed.error.issues.map((i) => `${i.path.join('.')}: ${i.message}`),
    };
  }
  let map = parsed.data;
  let check = validateMapStructure(map);
  if (!check.ok) {
    map = repairMapStructure(map);
    check = validateMapStructure(map);
    if (!check.ok) return { ok: false, errors: check.errors };
  }
  return { ok: true, map, warnings: check.warnings };
}

let counter = 0;
export function genId(prefix = 'n') {
  counter += 1;
  return `${prefix}_${Date.now().toString(36)}${Math.random().toString(36).slice(2, 7)}${counter}`;
}

/** A minimal empty-but-valid process map used for new blank processes. */
export function blankMap(name = 'Untitled process') {
  const laneId = genId('lane');
  const startId = genId('n');
  const taskId = genId('n');
  const endId = genId('n');
  return ProcessMapSchema.parse({
    name,
    type: 'swimlane',
    lanes: [{ id: laneId, name: 'Team', kind: 'team', order: 0 }],
    nodes: [
      { id: startId, type: 'start', label: 'Start', laneId },
      { id: taskId, type: 'task', label: 'New activity', laneId },
      { id: endId, type: 'end', label: 'End', laneId },
    ],
    edges: [
      { id: genId('e'), source: startId, target: taskId },
      { id: genId('e'), source: taskId, target: endId },
    ],
  });
}
